DROP TABLE IF EXISTS album;
CREATE TABLE album (
 id INT AUTO_INCREMENT NOT NULL,
 released VARCHAR(128) NOT NULL,
 price VARCHAR(20) NOT NULL,
 title VARCHAR(255) NOT NULL,
 author VARCHAR(128) NOT NULL,
 PRIMARY KEY (`id`)
);
